---
- name: setup manjaro on RPI4
  hosts: localhost
  become: yes

  tasks:
    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
    - name: packages
      pacman:
        name:
          - vim
          - git
          - i3-wm
          - yubikey-manager
        state: present

    - name: Test for entry mouse poll
      command: 'grep "usbhid.mousepoll=0" /boot/cmdline.txt'
      register: test_grep_mousepoll
      ignore_errors: yes

    - name: cmdline mouse poll
      lineinfile:
        path: /boot/cmdline.txt
        backrefs: True
        state: present
        regexp: '(.*)$'
        line: '\1 usbhid.mousepoll=0'
      when: test_grep_mousepoll.stdout == ""

    - name: enable pcscd
      systemd:
        name: pcscd.service
        enabled: yes
        state: started
